package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AveriasTarjetas generated by hbm2java
 */
@Entity
@Table(name = "averiasTarjetas")
public class AveriasTarjetas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idaveriaTarjeta;
	private Operadores operadores;
	private Tarjetas tarjetasByTarjetaNueva;
	private Tarjetas tarjetasByTarjetaAntigua;
	private Date fechaAveriaTarjeta;
	private Date fechaEntregaTarjeta;
	private Date fechabaja;
	private String motivobaja;
	private String historialAveria;
	private String observaciones;

	public AveriasTarjetas() {
	}

	public AveriasTarjetas(Tarjetas tarjetasByTarjetaNueva, Tarjetas tarjetasByTarjetaAntigua) {
		this.tarjetasByTarjetaNueva = tarjetasByTarjetaNueva;
		this.tarjetasByTarjetaAntigua = tarjetasByTarjetaAntigua;
	}

	public AveriasTarjetas(Operadores operadores, Tarjetas tarjetasByTarjetaNueva, Tarjetas tarjetasByTarjetaAntigua,
			Date fechaAveriaTarjeta, Date fechaEntregaTarjeta, Date fechabaja, String motivobaja,
			String historialAveria, String observaciones) {
		this.operadores = operadores;
		this.tarjetasByTarjetaNueva = tarjetasByTarjetaNueva;
		this.tarjetasByTarjetaAntigua = tarjetasByTarjetaAntigua;
		this.fechaAveriaTarjeta = fechaAveriaTarjeta;
		this.fechaEntregaTarjeta = fechaEntregaTarjeta;
		this.fechabaja = fechabaja;
		this.motivobaja = motivobaja;
		this.historialAveria = historialAveria;
		this.observaciones = observaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idaveriaTarjeta", unique = true, nullable = false)
	public Integer getIdaveriaTarjeta() {
		return this.idaveriaTarjeta;
	}

	public void setIdaveriaTarjeta(Integer idaveriaTarjeta) {
		this.idaveriaTarjeta = idaveriaTarjeta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idOperador")
	public Operadores getOperadores() {
		return this.operadores;
	}

	public void setOperadores(Operadores operadores) {
		this.operadores = operadores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tarjetaNueva", nullable = false)
	public Tarjetas getTarjetasByTarjetaNueva() {
		return this.tarjetasByTarjetaNueva;
	}

	public void setTarjetasByTarjetaNueva(Tarjetas tarjetasByTarjetaNueva) {
		this.tarjetasByTarjetaNueva = tarjetasByTarjetaNueva;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tarjetaAntigua", nullable = false)
	public Tarjetas getTarjetasByTarjetaAntigua() {
		return this.tarjetasByTarjetaAntigua;
	}

	public void setTarjetasByTarjetaAntigua(Tarjetas tarjetasByTarjetaAntigua) {
		this.tarjetasByTarjetaAntigua = tarjetasByTarjetaAntigua;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaAveriaTarjeta", length = 10)
	public Date getFechaAveriaTarjeta() {
		return this.fechaAveriaTarjeta;
	}

	public void setFechaAveriaTarjeta(Date fechaAveriaTarjeta) {
		this.fechaAveriaTarjeta = fechaAveriaTarjeta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaEntregaTarjeta", length = 10)
	public Date getFechaEntregaTarjeta() {
		return this.fechaEntregaTarjeta;
	}

	public void setFechaEntregaTarjeta(Date fechaEntregaTarjeta) {
		this.fechaEntregaTarjeta = fechaEntregaTarjeta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechabaja", length = 10)
	public Date getFechabaja() {
		return this.fechabaja;
	}

	public void setFechabaja(Date fechabaja) {
		this.fechabaja = fechabaja;
	}

	@Column(name = "motivobaja", length = 250)
	public String getMotivobaja() {
		return this.motivobaja;
	}

	public void setMotivobaja(String motivobaja) {
		this.motivobaja = motivobaja;
	}

	@Column(name = "historialAveria", length = 250)
	public String getHistorialAveria() {
		return this.historialAveria;
	}

	public void setHistorialAveria(String historialAveria) {
		this.historialAveria = historialAveria;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
