package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompaniasTerminales generated by hbm2java
 */
@Entity
@Table(name = "companiasTerminales")
public class CompaniasTerminales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCompaniaTerminal;
	private String companiasTerminal;
	private Set<Terminales> terminaleses = new HashSet<Terminales>(0);

	public CompaniasTerminales() {
	}

	public CompaniasTerminales(String companiasTerminal) {
		this.companiasTerminal = companiasTerminal;
	}

	public CompaniasTerminales(String companiasTerminal, Set<Terminales> terminaleses) {
		this.companiasTerminal = companiasTerminal;
		this.terminaleses = terminaleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCompaniaTerminal", unique = true, nullable = false)
	public Integer getIdCompaniaTerminal() {
		return this.idCompaniaTerminal;
	}

	public void setIdCompaniaTerminal(Integer idCompaniaTerminal) {
		this.idCompaniaTerminal = idCompaniaTerminal;
	}

	@Column(name = "companiasTerminal", nullable = false, length = 70)
	public String getCompaniasTerminal() {
		return this.companiasTerminal;
	}

	public void setCompaniasTerminal(String companiasTerminal) {
		this.companiasTerminal = companiasTerminal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companiasTerminales")
	public Set<Terminales> getTerminaleses() {
		return this.terminaleses;
	}

	public void setTerminaleses(Set<Terminales> terminaleses) {
		this.terminaleses = terminaleses;
	}

	@Override
    public String toString() {
        return String.format("%s[id=%d]", getClass().getSimpleName(), getIdCompaniaTerminal());
    }
	
}
