package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DepartamentosAyto generated by hbm2java
 */
@Entity
@Table(name = "departamentosAyto")
public class DepartamentosAyto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDepAyto;
	private String nomDep;
	private String edificio;
	private String planta;
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

	public DepartamentosAyto() {
	}

	public DepartamentosAyto(String nomDep) {
		this.nomDep = nomDep;
	}

	public DepartamentosAyto(String nomDep, String edificio, String planta, Set<Usuarios> usuarioses) {
		this.nomDep = nomDep;
		this.edificio = edificio;
		this.planta = planta;
		this.usuarioses = usuarioses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDepAyto", unique = true, nullable = false)
	public Integer getIdDepAyto() {
		return this.idDepAyto;
	}

	public void setIdDepAyto(Integer idDepAyto) {
		this.idDepAyto = idDepAyto;
	}

	@Column(name = "nomDep", nullable = false, length = 70)
	public String getNomDep() {
		return this.nomDep;
	}

	public void setNomDep(String nomDep) {
		this.nomDep = nomDep;
	}

	@Column(name = "edificio", length = 70)
	public String getEdificio() {
		return this.edificio;
	}

	public void setEdificio(String edificio) {
		this.edificio = edificio;
	}

	@Column(name = "planta", length = 70)
	public String getPlanta() {
		return this.planta;
	}

	public void setPlanta(String planta) {
		this.planta = planta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamentosAyto")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}
	
	@Override
    public String toString() {
        return String.format("%s[id=%d]", getClass().getSimpleName(), getIdDepAyto());
    }
		//Necesario para que guarde los cambios cuando se modifican valores en los despleglable.
	@Override
    public boolean equals(Object obj) {
          if (getClass() != obj.getClass()) 
              return false;
          return idDepAyto.equals(((DepartamentosAyto)obj).idDepAyto);
    }
	
}
