package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dispositivos generated by hbm2java
 */
@Entity
@Table(name = "dispositivos")
public class Dispositivos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDispositivo;
	private ModelosDispositivos modelosDispositivos;
	private String numeroserieDispositivo;
	private String tipoDispositivo;
	private Boolean activo;
	private String observaciones;
	public Dispositivos() {
	}

	public Dispositivos(String numeroserieDispositivo, String tipoDispositivo) {
		this.numeroserieDispositivo = numeroserieDispositivo;
		this.tipoDispositivo = tipoDispositivo;
	}

	public Dispositivos(ModelosDispositivos modelosDispositivos, String numeroserieDispositivo, String tipoDispositivo,
			Boolean activo, String observaciones) {
		this.modelosDispositivos = modelosDispositivos;
		this.numeroserieDispositivo = numeroserieDispositivo;
		this.tipoDispositivo = tipoDispositivo;
		this.activo = activo;
		this.observaciones = observaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDispositivo", unique = true, nullable = false)
	public Integer getIdDispositivo() {
		return this.idDispositivo;
	}

	public void setIdDispositivo(Integer idDispositivo) {
		this.idDispositivo = idDispositivo;
	}

	@ManyToOne
	@JoinColumn(name = "idModeloDispositivo")
	public ModelosDispositivos getModelosDispositivos() {
		return this.modelosDispositivos;
	}

	public void setModelosDispositivos(ModelosDispositivos modelosDispositivos) {
		this.modelosDispositivos = modelosDispositivos;
	}

	
	
	@Column(name = "numeroserie_Dispositivo", nullable = false, length = 70)
	public String getNumeroserieDispositivo() {
		return this.numeroserieDispositivo;
	}

	public void setNumeroserieDispositivo(String numeroserieDispositivo) {
		this.numeroserieDispositivo = numeroserieDispositivo;
	}

	
	@Column(name = "tipo_Dispositivo", nullable = false, length = 70)
	public String getTipoDispositivo() {
		return this.tipoDispositivo;
	}

	public void setTipoDispositivo(String tipoDispositivo) {
		this.tipoDispositivo = tipoDispositivo;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
