package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entregas generated by hbm2java
 */
@Entity
@Table(name = "entregas")
public class Entregas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEntrega;
	private Operadores operadores;
	private Tarjetas tarjetas;
	private Terminales terminales;
	private Usuarios usuarios;
	private Date fechaEntrega;
	private String observaciones;
	private String historialEntrega;

	public Entregas() {
	}

	public Entregas(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public Entregas(Operadores operadores, Tarjetas tarjetas, Terminales terminales, Usuarios usuarios,
			Date fechaEntrega, String observaciones, String historialEntrega) {
		this.operadores = operadores;
		this.tarjetas = tarjetas;
		this.terminales = terminales;
		this.usuarios = usuarios;
		this.fechaEntrega = fechaEntrega;
		this.observaciones = observaciones;
		this.historialEntrega = historialEntrega;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEntrega", unique = true, nullable = false)
	public Integer getIdEntrega() {
		return this.idEntrega;
	}

	public void setIdEntrega(Integer idEntrega) {
		this.idEntrega = idEntrega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idOperador")
	public Operadores getOperadores() {
		return this.operadores;
	}

	public void setOperadores(Operadores operadores) {
		this.operadores = operadores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTarjeta")
	public Tarjetas getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(Tarjetas tarjetas) {
		this.tarjetas = tarjetas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTerminal")
	public Terminales getTerminales() {
		return this.terminales;
	}

	public void setTerminales(Terminales terminales) {
		this.terminales = terminales;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaEntrega", nullable = false, length = 10)
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "historialEntrega", length = 250)
	public String getHistorialEntrega() {
		return this.historialEntrega;
	}

	public void setHistorialEntrega(String historialEntrega) {
		this.historialEntrega = historialEntrega;
	}

}
