package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadosTerminales generated by hbm2java
 */
@Entity
@Table(name = "estadosTerminales")
public class EstadosTerminales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEstadoTerminal;
	private String estado;
	private Set<Terminales> terminaleses = new HashSet<Terminales>(0);
	private Set<HistEstados> histEstadoses = new HashSet<HistEstados>(0);

	public EstadosTerminales() {
	}

	public EstadosTerminales(String estado) {
		this.estado = estado;
	}

	public EstadosTerminales(String estado, Set<Terminales> terminaleses, Set<HistEstados> histEstadoses) {
		this.estado = estado;
		this.terminaleses = terminaleses;
		this.histEstadoses = histEstadoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEstadoTerminal", unique = true, nullable = false)
	public Integer getIdEstadoTerminal() {
		return this.idEstadoTerminal;
	}

	public void setIdEstadoTerminal(Integer idEstadoTerminal) {
		this.idEstadoTerminal = idEstadoTerminal;
	}

	@Column(name = "estado", nullable = false, length = 70)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadosTerminales")
	public Set<Terminales> getTerminaleses() {
		return this.terminaleses;
	}

	public void setTerminaleses(Set<Terminales> terminaleses) {
		this.terminaleses = terminaleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadosTerminales")
	public Set<HistEstados> getHistEstadoses() {
		return this.histEstadoses;
	}

	public void setHistEstadoses(Set<HistEstados> histEstadoses) {
		this.histEstadoses = histEstadoses;
	}
	
	@Override
    public String toString() {
        return String.format("%s[id=%d]", getClass().getSimpleName(), getIdEstadoTerminal());
    }

}
