package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistEstados generated by hbm2java
 */
@Entity
@Table(name = "histEstados")
public class HistEstados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idHistEstado;
	private EstadosTerminales estadosTerminales;
	private Terminales terminales;
	private Date fechaHistEstado;
	private String descripcionHistestado;
	private String observaciones;

	public HistEstados() {
	}

	public HistEstados(EstadosTerminales estadosTerminales, Terminales terminales, Date fechaHistEstado,
			String descripcionHistestado, String observaciones) {
		this.estadosTerminales = estadosTerminales;
		this.terminales = terminales;
		this.fechaHistEstado = fechaHistEstado;
		this.descripcionHistestado = descripcionHistestado;
		this.observaciones = observaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idHistEstado", unique = true, nullable = false)
	public Integer getIdHistEstado() {
		return this.idHistEstado;
	}

	public void setIdHistEstado(Integer idHistEstado) {
		this.idHistEstado = idHistEstado;
	}

	@ManyToOne
	@JoinColumn(name = "idEstadoTerminal")
	public EstadosTerminales getEstadosTerminales() {
		return this.estadosTerminales;
	}

	public void setEstadosTerminales(EstadosTerminales estadosTerminales) {
		this.estadosTerminales = estadosTerminales;
	}

	@ManyToOne
	@JoinColumn(name = "idTerminal")
	public Terminales getTerminales() {
		return this.terminales;
	}

	public void setTerminales(Terminales terminales) {
		this.terminales = terminales;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaHistEstado", length = 10)
	public Date getFechaHistEstado() {
		return this.fechaHistEstado;
	}

	public void setFechaHistEstado(Date fechaHistEstado) {
		this.fechaHistEstado = fechaHistEstado;
	}

	@Column(name = "descripcionHistestado", length = 250)
	public String getDescripcionHistestado() {
		return this.descripcionHistestado;
	}

	public void setDescripcionHistestado(String descripcionHistestado) {
		this.descripcionHistestado = descripcionHistestado;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
