package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModelosDispositivos generated by hbm2java
 */
@Entity
@Table(name = "modelosdispositivos")
public class ModelosDispositivos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idModeloDispositivo;
	private Marcas marcas;
	private String modeloDispositivo;
	private Set<Dispositivos> dispositivoses = new HashSet<Dispositivos>(0);

	public ModelosDispositivos() {
	}

	public ModelosDispositivos(String modeloDispositivo) {
		this.modeloDispositivo = modeloDispositivo;
	}

	public ModelosDispositivos(Marcas marcas, String modeloDispositivo, Set<Dispositivos> dispositivoses) {
		this.marcas = marcas;
		this.modeloDispositivo = modeloDispositivo;
		this.dispositivoses = dispositivoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModeloDispositivo", unique = true, nullable = false)
	public Integer getIdModeloDispositivo() {
		return this.idModeloDispositivo;
	}

	public void setIdModeloDispositivo(Integer idModeloDispositivo) {
		this.idModeloDispositivo = idModeloDispositivo;
	}

	@ManyToOne
	@JoinColumn(name = "idMarca")
	public Marcas getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Marcas marcas) {
		this.marcas = marcas;
	}

	@Column(name = "modelo_Dispositivo", nullable = false, length = 70)
	public String getModeloDispositivo() {
		return this.modeloDispositivo;
	}

	public void setModeloDispositivo(String modeloDispositivo) {
		this.modeloDispositivo = modeloDispositivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelosDispositivos")
	public Set<Dispositivos> getDispositivoses() {
		return this.dispositivoses;
	}

	public void setDispositivoses(Set<Dispositivos> dispositivoses) {
		this.dispositivoses = dispositivoses;
	}

}
