package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModelosTerminales generated by hbm2java
 */
@Entity
@Table(name = "modelosTerminales")
public class ModelosTerminales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idModeloTerminal;
	private Marcas marcas;
	private String modelos;
	private Set<Terminales> terminaleses = new HashSet<Terminales>(0);

	public ModelosTerminales() {
	}

	public ModelosTerminales(String modelos) {
		this.modelos = modelos;
	}

	public ModelosTerminales(Marcas marcas, String modelos, Set<Terminales> terminaleses) {
		this.marcas = marcas;
		this.modelos = modelos;
		this.terminaleses = terminaleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModeloTerminal", unique = true, nullable = false)
	public Integer getIdModeloTerminal() {
		return this.idModeloTerminal;
	}

	public void setIdModeloTerminal(Integer idModeloTerminal) {
		this.idModeloTerminal = idModeloTerminal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMarca")
	public Marcas getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Marcas marcas) {
		this.marcas = marcas;
	}

	@Column(name = "modelos", nullable = false, length = 70)
	public String getModelos() {
		return this.modelos;
	}

	public void setModelos(String modelos) {
		this.modelos = modelos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelosTerminales")
	public Set<Terminales> getTerminaleses() {
		return this.terminaleses;
	}

	public void setTerminaleses(Set<Terminales> terminaleses) {
		this.terminaleses = terminaleses;
	}

}
