package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operadores generated by hbm2java
 */
@Entity
@Table(name = "operadores")
public class Operadores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idOperador;
	private String usuarioOperador;
	private Set<Entregas> entregases = new HashSet<Entregas>(0);
	private Set<AveriasTerminales> averiasTerminaleses = new HashSet<AveriasTerminales>(0);
	private Set<AveriasTarjetas> averiasTarjetases = new HashSet<AveriasTarjetas>(0);

	public Operadores() {
	}

	public Operadores(String usuarioOperador) {
		this.usuarioOperador = usuarioOperador;
	}

	public Operadores(String usuarioOperador, Set<Entregas> entregases, Set<AveriasTerminales> averiasTerminaleses, Set<AveriasTarjetas> averiasTarjetases) {
		this.usuarioOperador = usuarioOperador;
		this.entregases = entregases;
		this.averiasTerminaleses = averiasTerminaleses;
		this.averiasTarjetases = averiasTarjetases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idOperador", unique = true, nullable = false)
	public Integer getIdOperador() {
		return this.idOperador;
	}

	public void setIdOperador(Integer idOperador) {
		this.idOperador = idOperador;
	}

	@Column(name = "usuarioOperador", nullable = false, length = 70)
	public String getUsuarioOperador() {
		return this.usuarioOperador;
	}

	public void setUsuarioOperador(String usuarioOperador) {
		this.usuarioOperador = usuarioOperador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadores")
	public Set<Entregas> getEntregases() {
		return this.entregases;
	}

	public void setEntregases(Set<Entregas> entregases) {
		this.entregases = entregases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadores")
	public Set<AveriasTerminales> getAveriasTerminaleses() {
		return this.averiasTerminaleses;
	}

	public void setAveriasTerminaleses(Set<AveriasTerminales> averiasTerminaleses) {
		this.averiasTerminaleses = averiasTerminaleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadores")
	public Set<AveriasTarjetas> getAveriasTarjetases() {
		return this.averiasTarjetases;
	}

	public void setAveriasTarjetases(Set<AveriasTarjetas> averiasTarjetases) {
		this.averiasTarjetases = averiasTarjetases;
	}

}
