package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tarjetas generated by hbm2java
 */
@Entity
@Table(name = "tarjetas", uniqueConstraints = { @UniqueConstraint(columnNames = "icc"),
		@UniqueConstraint(columnNames = "numCorto"), @UniqueConstraint(columnNames = "numLargo") })
public class Tarjetas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTarjeta;
	private EstadosTarjetas estadosTarjetas;
	private TiposContratos tiposContratos;
	private TiposTarifas tiposTarifas;
	private TiposTarjetas tiposTarjetas;
	private int pin;
	private int puk;
	private String icc;
	private String numCorto;
	private String numLargo;
	private Boolean disponible;
	private String historialAveria;
	private String observaciones;
	private String cambioNumero;
	private Date fechaAlta;
	private Date fechaBaja;
	private String motivoBaja;
	private Set<Entregas> entregases = new HashSet<Entregas>(0);
	private Set<AveriasTarjetas> averiasTarjetasesForTarjetaNueva = new HashSet<AveriasTarjetas>(0);
	private Set<AveriasTarjetas> averiasTarjetasesForTarjetaAntigua = new HashSet<AveriasTarjetas>(0);

	public Tarjetas() {
	}

	public Tarjetas(int pin, int puk, String icc, String numCorto, String numLargo) {
		this.pin = pin;
		this.puk = puk;
		this.icc = icc;
		this.numCorto = numCorto;
		this.numLargo = numLargo;
	}

	public Tarjetas(EstadosTarjetas estadosTarjetas, TiposContratos tiposContratos, TiposTarifas tiposTarifas,
			TiposTarjetas tiposTarjetas, int pin, int puk, String icc, String numCorto, String numLargo,
			Boolean disponible, String historialAveria, String observaciones, String cambioNumero, Date fechaAlta,
			Date fechaBaja, String motivoBaja, Set<Entregas> entregases, Set<AveriasTarjetas> averiasTarjetasesForTarjetaNueva,
			Set<AveriasTarjetas> averiasTarjetasesForTarjetaAntigua) {
		this.estadosTarjetas = estadosTarjetas;
		this.tiposContratos = tiposContratos;
		this.tiposTarifas = tiposTarifas;
		this.tiposTarjetas = tiposTarjetas;
		this.pin = pin;
		this.puk = puk;
		this.icc = icc;
		this.numCorto = numCorto;
		this.numLargo = numLargo;
		this.disponible = disponible;
		this.historialAveria = historialAveria;
		this.observaciones = observaciones;
		this.cambioNumero = cambioNumero;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.motivoBaja = motivoBaja;
		this.entregases = entregases;
		this.averiasTarjetasesForTarjetaNueva = averiasTarjetasesForTarjetaNueva;
		this.averiasTarjetasesForTarjetaAntigua = averiasTarjetasesForTarjetaAntigua;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTarjeta", unique = true, nullable = false)
	public Integer getIdTarjeta() {
		return this.idTarjeta;
	}

	public void setIdTarjeta(Integer idTarjeta) {
		this.idTarjeta = idTarjeta;
	}

	@ManyToOne
	@JoinColumn(name = "idEstadoTarjeta")
	public EstadosTarjetas getEstadosTarjetas() {
		return this.estadosTarjetas;
	}

	public void setEstadosTarjetas(EstadosTarjetas estadosTarjetas) {
		this.estadosTarjetas = estadosTarjetas;
	}

	@ManyToOne
	@JoinColumn(name = "idTipoContrato")
	public TiposContratos getTiposContratos() {
		return this.tiposContratos;
	}

	public void setTiposContratos(TiposContratos tiposContratos) {
		this.tiposContratos = tiposContratos;
	}

	@ManyToOne
	@JoinColumn(name = "idTipoTarifa")
	public TiposTarifas getTiposTarifas() {
		return this.tiposTarifas;
	}

	public void setTiposTarifas(TiposTarifas tiposTarifas) {
		this.tiposTarifas = tiposTarifas;
	}

	@ManyToOne
	@JoinColumn(name = "idTipoTarjeta")
	public TiposTarjetas getTiposTarjetas() {
		return this.tiposTarjetas;
	}

	public void setTiposTarjetas(TiposTarjetas tiposTarjetas) {
		this.tiposTarjetas = tiposTarjetas;
	}

	@Column(name = "pin", nullable = false)
	public int getPin() {
		return this.pin;
	}

	public void setPin(int pin) {
		this.pin = pin;
	}

	@Column(name = "puk", nullable = false)
	public int getPuk() {
		return this.puk;
	}

	public void setPuk(int puk) {
		this.puk = puk;
	}

	@Column(name = "icc", unique = true, nullable = false, length = 40)
	public String getIcc() {
		return this.icc;
	}

	public void setIcc(String icc) {
		this.icc = icc;
	}

	@Column(name = "numCorto", unique = true, nullable = false, length = 70)
	public String getNumCorto() {
		return this.numCorto;
	}

	public void setNumCorto(String numCorto) {
		this.numCorto = numCorto;
	}

	@Column(name = "numLargo", unique = true, nullable = false, length = 70)
	public String getNumLargo() {
		return this.numLargo;
	}

	public void setNumLargo(String numLargo) {
		this.numLargo = numLargo;
	}

	@Column(name = "disponible")
	public Boolean getDisponible() {
		return this.disponible;
	}

	public void setDisponible(Boolean disponible) {
		this.disponible = disponible;
	}

	@Column(name = "historialAveria", length = 250)
	public String getHistorialAveria() {
		return this.historialAveria;
	}

	public void setHistorialAveria(String historialAveria) {
		this.historialAveria = historialAveria;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "cambioNumero", length = 90)
	public String getCambioNumero() {
		return this.cambioNumero;
	}

	public void setCambioNumero(String cambioNumero) {
		this.cambioNumero = cambioNumero;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", length = 10)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 10)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@Column(name = "motivo_baja", length = 250)
	public String getMotivoBaja() {
		return this.motivoBaja;
	}

	public void setMotivoBaja(String motivoBaja) {
		this.motivoBaja = motivoBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjetas")
	public Set<Entregas> getEntregases() {
		return this.entregases;
	}

	public void setEntregases(Set<Entregas> entregases) {
		this.entregases = entregases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjetasByTarjetaNueva")
	public Set<AveriasTarjetas> getAveriasTarjetasesForTarjetaNueva() {
		return this.averiasTarjetasesForTarjetaNueva;
	}

	public void setAveriasTarjetasesForTarjetaNueva(Set<AveriasTarjetas> averiasTarjetasesForTarjetaNueva) {
		this.averiasTarjetasesForTarjetaNueva = averiasTarjetasesForTarjetaNueva;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjetasByTarjetaAntigua")
	public Set<AveriasTarjetas> getAveriasTarjetasesForTarjetaAntigua() {
		return this.averiasTarjetasesForTarjetaAntigua;
	}

	public void setAveriasTarjetasesForTarjetaAntigua(Set<AveriasTarjetas> averiasTarjetasesForTarjetaAntigua) {
		this.averiasTarjetasesForTarjetaAntigua = averiasTarjetasesForTarjetaAntigua;
	}
	
	@Override
    public String toString() {
        return String.format("%s[id=%d]", getClass().getSimpleName(), getIdTarjeta());
    }
	
	@Override
    public boolean equals(Object obj) {
          if (getClass() != obj.getClass()) 
              return false;
          return idTarjeta.equals(((Tarjetas)obj).idTarjeta);
    }

}
