package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposTerminales generated by hbm2java
 */
@Entity
@Table(name = "tiposTerminales")
public class TiposTerminales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTipoTerminal;
	private String tipoTerminal;
	private Set<Terminales> terminaleses = new HashSet<Terminales>(0);

	public TiposTerminales() {
	}

	public TiposTerminales(String tipoTerminal) {
		this.tipoTerminal = tipoTerminal;
	}

	public TiposTerminales(String tipoTerminal, Set<Terminales> terminaleses) {
		this.tipoTerminal = tipoTerminal;
		this.terminaleses = terminaleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoTerminal", unique = true, nullable = false)
	public Integer getIdTipoTerminal() {
		return this.idTipoTerminal;
	}

	public void setIdTipoTerminal(Integer idTipoTerminal) {
		this.idTipoTerminal = idTipoTerminal;
	}

	@Column(name = "tipoTerminal", nullable = false, length = 70)
	public String getTipoTerminal() {
		return this.tipoTerminal;
	}

	public void setTipoTerminal(String tipoTerminal) {
		this.tipoTerminal = tipoTerminal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposTerminales")
	public Set<Terminales> getTerminaleses() {
		return this.terminaleses;
	}

	public void setTerminaleses(Set<Terminales> terminaleses) {
		this.terminaleses = terminaleses;
	}
	
	@Override
    public String toString() {
        return String.format("%s[id=%d]", getClass().getSimpleName(), getIdTipoTerminal());
    }

}
