package com.ayto.proyecto.modelo;
// Generated 05-may-2018 19:20:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposContratos generated by hbm2java
 */
@Entity
@Table(name = "tiposContratos")
public class TiposContratos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTipoContrato;
	private String tipoContrato;
	private String observaciones;
	private Boolean activo;
	private Set<Tarjetas> tarjetases = new HashSet<Tarjetas>(0);

	public TiposContratos() {
	}

	public TiposContratos(String tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	public TiposContratos(String tipoContrato, String observaciones, Boolean activo, Set<Tarjetas> tarjetases) {
		this.tipoContrato = tipoContrato;
		this.observaciones = observaciones;
		this.activo = activo;
		this.tarjetases = tarjetases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoContrato", unique = true, nullable = false)
	public Integer getIdTipoContrato() {
		return this.idTipoContrato;
	}

	public void setIdTipoContrato(Integer idTipoContrato) {
		this.idTipoContrato = idTipoContrato;
	}

	@Column(name = "tipoContrato", nullable = false, length = 70)
	public String getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(String tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposContratos")
	public Set<Tarjetas> getTarjetases() {
		return this.tarjetases;
	}

	public void setTarjetases(Set<Tarjetas> tarjetases) {
		this.tarjetases = tarjetases;
	}

	@Override
    public String toString() {
        return String.format("%s[id=%d]", getClass().getSimpleName(), getIdTipoContrato());
    }
	
	@Override
    public boolean equals(Object obj) {
          if (getClass() != obj.getClass()) 
              return false;
          return idTipoContrato.equals(((TiposContratos)obj).idTipoContrato);
    }
}
